version: '3.5'
services:
  ubuntu:
    image: ubuntu:latest
    working_dir: /app
    volumes:
      - ./:/app/
    environment:
      - GITHUB_API_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    command: tail -f /dev/null
